# Generated by Django 5.2.2 on 2025-06-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Browser page title', max_length=255)),
                ('banner_heading', models.CharField(help_text='Main heading on the banner', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('venue', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Event Page',
                'verbose_name_plural': 'Event Pages',
                'ordering': ['event_date'],
            },
        ),
    ]
