# Generated by Django 5.1.2 on 2025-06-23 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_speaker_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Exhibitor', 'Exhibitor'), ('Sponsor', 'Sponsor')], max_length=50)),
                ('company_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('whatsapp', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
