# Generated by Django 5.1.2 on 2025-06-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_alter_startuppitchapplication_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaPartnerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_type', models.CharField(choices=[('media', 'Media Partner'), ('community', 'Community Partner')], max_length=20)),
                ('events', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
