# Generated by Django 5.1.2 on 2025-06-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_sponsorinquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('total_employees', models.PositiveIntegerField()),
                ('speaker_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('isd_code', models.CharField(max_length=10)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('slot', models.CharField(max_length=255)),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
