# Generated by Django 5.1.2 on 2025-07-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_speakerapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Speaker', 'Speaker'), ('Exhibitor', 'Exhibitor'), ('Sponsor', 'Sponsor'), ('Partner', 'Partner'), ('Visitor', 'Visitor')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=255)),
                ('isd_code', models.CharField(max_length=10)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
