# Generated by Django 5.1.2 on 2025-07-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_internshipapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipapplication',
            name='contact',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='department',
            field=models.CharField(choices=[('Marketing', 'Marketing'), ('Tech', 'Tech / Development'), ('Events', 'Events'), ('Design', 'Design'), ('Other', 'Other')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='motivation',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='program',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='school',
            field=models.CharField(default='0000000000', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='resume',
            field=models.FileField(upload_to='internship_resumes/'),
        ),
    ]
