# Generated by Django 5.1.2 on 2025-08-08 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_freepassregistrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorinquiry',
            name='tier',
            field=models.CharField(blank=True, choices=[('Diamond', 'Diamond'), ('Platinum', 'Platinum'), ('Gold', 'Gold'), ('Silver', 'Silver')], max_length=20, null=True),
        ),
    ]
