# Generated by Django 5.1.2 on 2025-08-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_sponsorinquiry_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitregistration',
            name='type',
            field=models.CharField(choices=[('Startup Booth', 'Startup Booth'), ('Growth Booth', 'Growth Booth'), ('Enterprise Booth', 'Enterprise Booth')], max_length=50),
        ),
    ]
