# Generated by Django 5.1.2 on 2025-09-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_alter_exhibitregistration_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitRegistration2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('company_size', models.CharField(choices=[('1-20', '1–20'), ('21-100', '21–100'), ('100+', '100+')], max_length=16)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('website', models.URLField(blank=True)),
                ('contact_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('tier', models.CharField(choices=[('startup', 'Startup Booth'), ('growth', 'Growth Booth'), ('enterprise', 'Enterprise Booth')], max_length=20)),
                ('pricing_mode', models.CharField(choices=[('early', 'Early'), ('regular', 'Regular')], default='early', max_length=10)),
                ('base_price', models.PositiveIntegerField(default=0, help_text='PHP, no decimals')),
                ('total_price', models.PositiveIntegerField(default=0, help_text='PHP, no decimals')),
                ('add_logo', models.BooleanField(default=False)),
                ('add_power', models.BooleanField(default=False)),
                ('add_leads', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('agree', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exhibit Registration',
                'verbose_name_plural': 'Exhibit Registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
